### ISSUE TITLE
Haxe Roundup 327 29-06-2015 - 05-07-2015

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#160]
To add to the roundup todo list, use the following markdown format.
```
- [ ] optional description [link name](/link/to/item) by [Persons Name](link/to/person)
```

**Comment by NicoM1** [comment]
- [ ] slickrock.io, modern, minimal, and perfectly embeddable chat site. (not yet officially launched, should be by time of roundup or I will alert you otherwise). also if it seems appropriate you could include the link to donations: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=nico%2emay99%40gmail%2ecom&lc=CA&item_name=slickrock%2eio&currency_code=CAD&bn=PP%2dDonationsBF%3a%26text%3ddonate%2e%3aNonHosted

written completely in haxe, using @fponticelli's Abe library on the backend.

also maybe you could use one of the marketting images, this one is my favourite: http://chat.slickrock.io/bin/img/demo_onlog.jpg

**Comment by skial** [comment]
I'm fine with mentioning slickrocks donations @NicoM1 :+1:

**Comment by NicoM1** [comment]
Cool, thanks, btw I disabled the bridge to irc, people were finding it
spammy, I'm a little bummed about it but hopefully in future a better
solution can be worked out

Nico

**Comment by skial** [comment]
- [ ] Hxml basics [article](https://twitter.com/Matt_Tuttle/status/615533637761568768)
- [ ] [Pic](https://twitter.com/bendmorris/status/615780238589427713) of an in-progress game boy emulator plus [source](https://twitter.com/bendmorris/status/616274513622249473)
- [ ] [Video](https://twitter.com/grayhaze/status/615913270642384896) of Kevin's intro to haxe talk now available
- [ ] [Homebrew](https://twitter.com/sudoestegames/status/616307574951014401) flappy bird running in the emulator mentioned above
- [ ] Custom [openfl shaders](https://twitter.com/larsiusprime/status/616325355847176193)
- [ ] HxInflate [article](https://twitter.com/proletariat_inc/status/616330407064272896)
- [ ] New jQuery externs have arrivied - check the [article](https://twitter.com/andy_li/status/616506128256630784)
- [ ] Shifter out on [iOS](https://twitter.com/bombocracker/status/616890056113029120)
- [ ] haxe watchify has been [released](https://twitter.com/lucamezzalira/status/6171075238800056320

**Comment by skial** [comment]
- [ ] Haxe and [the FBI](https://twitter.com/elsassph/status/615942366478864384)

**Comment by skial** [comment]
- [ ] [FrontJS](https://github.com/eduardo-costa/frontjs), Haxe powered MVC framework

**Comment by Gama11** [comment]
- [ ] [BabylonHx now has a website](http://community.openfl.org/t/babylonhx-cross-platform-3d-engine/1769)
