### ISSUE TITLE
Numbers are blocks

### ISSUE THREAD

**Issue by markknol** [skial/haxe.io#201]
![image](https://cloud.githubusercontent.com/assets/576184/10620235/3a85cbc8-777a-11e5-88ae-bced6439f1fc.png)

Seen in Chrome 46.0.2490.71 m

**Comment by skial** [comment]
That's weird, as I'm on the exact same version of Chome as you without any issues.

My first thought was normalize-opentype.css could be the culprit and its _possible_ due to https://github.com/kennethormandy/normalize-opentype.css/issues/19, with the difference being the font for `h1` is just Arial.

1. Does disabling `-webkit-font-feature-settings` through the inspector make the numbers appear?
1. What OS are you on?

**Comment by skial** [comment]
- Chrome 46 on [Windows 10](https://saucelabs.com/tests/8e912f491cfa454fa811006b33e6635b), [Windows 8.1](https://saucelabs.com/tests/2177a69af5b6463f8aea0f5f3dc9340b), number alignment issues, via saucelabs.

Linux, XP, Windows 7, OS X 10.8 - 10.11 on Chrome 46 render the numbers.

**Comment by markknol** [comment]
It only appears on my windows 10 machine.

**Comment by markknol** [comment]
I never noticed this again, Ill close it.
