### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by Richard-Walton** [skial/haxe.io#240]
Don't know of a more appropriate place to put this, but, I get the following when trying to access haxe.io:
```
ERROR

The request could not be satisfied.

Bad request. 
Generated by cloudfront (CloudFront)
Request ID: zqjG0KDL3oGDijnOJPSzTDa4ITxxN74JcxUQgzZqsKKJpNNMyoi8Gw==
```

Given cloudfront is generating the error, it may well be something completely out of your control.  But I thought I'd raise it just incase.

**Comment by skial** [comment]
Thanks @Richard-Walton, thats all because of me. 

I'm moving dns services and I screwed up! No surprise really! :wink:

I'll keep this open until it's been fixed and _hopefully_ the dns propagated successfully!

You might want to try https://www.haxe.io which appears to still work for me, at the moment anyway :grin:

**Comment by Richard-Walton** [comment]
Thanks for the working link.  Good luck! :)

**Comment by skial** [comment]
https://haxe.io seems to propagating finally :smile:

**Comment by Richard-Walton** [comment]
:+1:
